In [3]:
import tensorflow as tf
t=tf.constant([[1.,2.,3.], [4.,5.,6.]])
#一个张量，表示具有两行三列浮点数的矩阵
#可进行如下操作：t+10, tf.square(t), t @ tf.transpose(t)

from tensorflow import keras
K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [6]:
#张量可以与NumPy配合使用：你可以用NumPy数组创建张量，反之亦然。
#，TensorFlow不会自动执行任何类型转换：如果你对不兼容类型的张量执行操作，会引发异常。例如，你不能把浮点张量和整数张量相加，甚至不能相加32位浮点和64位浮点
#可使用tf.cast()进行类型转换

v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v.assign(2*v)
v[0, 1].assign(42)
v[:, 2].assign([0., 1.])
v.scatter_nd_update(indices=[[0,0], [1,2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

### TensorFLow也支持其它数据结构：

**稀疏张量(tf.SparseTensor)**:有效地表示主要包含零的张量

**张量数组(tf.TensorArray)**:张量的列表。默认情况下，它们的大小是固定的，可以选择动态设置。它们包含的所有张量必须$ζ有相同的形状和数据类型

**不规则张量(tf.RaggedTensor)**:表示张量列表的静态列表，其中每个张量$ζ有相同的形状和数类型。t.ragged程序包包含用于不规则的张量的操作

**字符串张量(tf.string)**:它们表示字节字符串，而不是Unicode字符串，因此如果使用Unicode字符串创建字符串张量，则它将自动被编码为UTF-8

**集合(tf.sets)**:表示为常规张量或稀疏张量

**队列**:包含先进先出队列，优先级队列